param(
    [string]$Repo = "."
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$repoRoot =
    (Resolve-Path -LiteralPath $Repo -ErrorAction Stop).Path

$requiredTracked =
    @(
        "gradlew",
        "gradlew.bat",
        "gradle/wrapper/gradle-wrapper.jar",
        "gradle/wrapper/gradle-wrapper.properties",
        "gradle/verification-metadata.xml",
        "app/gradle.lockfile",
        "settings-gradle.lockfile"
    )

foreach ($relative in $requiredTracked) {
    $full = Join-Path $repoRoot $relative

    if (-not (Test-Path -LiteralPath $full -PathType Leaf)) {
        throw "Required supply-chain file is missing: $relative"
    }

    $tracked =
        @(
            & git -C $repoRoot ls-files -- $relative
        )

    if ($LASTEXITCODE -ne 0) {
        throw "git ls-files failed while checking: $relative"
    }

    if ($tracked.Count -ne 1) {
        throw "Required supply-chain file is not tracked exactly once: $relative"
    }
}

$gradlewMode =
    @(
        & git -C $repoRoot ls-files --stage -- gradlew
    )

if (
    $LASTEXITCODE -ne 0 -or
    $gradlewMode.Count -ne 1 -or
    -not ([string]$gradlewMode[0]).StartsWith("100755 ")
) {
    throw "gradlew must be tracked with mode 100755."
}

$metadataPath =
    Join-Path $repoRoot "gradle/verification-metadata.xml"

$metadataText =
    [IO.File]::ReadAllText(
        $metadataPath,
        [Text.Encoding]::UTF8
    )

try {
    [xml]$null = $metadataText
}
catch {
    throw "verification-metadata.xml is not valid XML."
}

$shaMatches =
    @(
        [regex]::Matches(
            $metadataText,
            '<sha256\s+value="([0-9a-fA-F]{64})"\s+origin="([^"]+)"\s*/>'
        )
    )

if ($shaMatches.Count -eq 0) {
    throw "No SHA-256 entries were found in verification metadata."
}

$nonGradleOrigin =
    @(
        $shaMatches |
            Where-Object {
                $_.Groups[2].Value -ne "Generated by Gradle"
            }
    )

if ($nonGradleOrigin.Count -gt 0) {
    throw (
        "Verification metadata contains SHA entries not marked " +
        "origin=`"Generated by Gradle`"."
    )
}

$allShaTags =
    @(
        [regex]::Matches(
            $metadataText,
            '<sha256\b[^>]*/>'
        )
    )

if ($allShaTags.Count -ne $shaMatches.Count) {
    throw (
        "Verification metadata contains malformed, missing-origin, " +
        "or non-SHA256 checksum entries."
    )
}

$settingsPath =
    Join-Path $repoRoot "settings.gradle.kts"

$settingsText =
    [IO.File]::ReadAllText(
        $settingsPath,
        [Text.Encoding]::UTF8
    )

if (
    $settingsText -notmatch
        'gradleProperty\("carepackUseMavenLocal"\)' -or
    $settingsText -notmatch
        '\.orElse\(false\)' -or
    $settingsText -notmatch
        'if\s*\(useMavenLocal\)\s*\{\s*mavenLocal\(\)'
) {
    throw (
        "mavenLocal must remain explicit opt-in and disabled by default."
    )
}

$scanFiles =
    @(
        "gradle/libs.versions.toml",
        "build.gradle.kts",
        "app/build.gradle.kts",
        "settings.gradle.kts"
    ) |
    ForEach-Object {
        Join-Path $repoRoot $_
    } |
    Where-Object {
        Test-Path -LiteralPath $_ -PathType Leaf
    }

$dynamicMatches =
    @(
        Select-String `
            -LiteralPath $scanFiles `
            -Pattern @(
                'SNAPSHOT',
                'latest\.',
                'version\s*=\s*"[^"]*\+"',
                'version\.ref\s*=\s*"[^"]*\+"'
            ) `
            -CaseSensitive:$false
    )

if ($dynamicMatches.Count -gt 0) {
    $dynamicMatches |
        ForEach-Object {
            Write-Host (
                "{0}:{1}: {2}" -f
                $_.Path,
                $_.LineNumber,
                $_.Line.Trim()
            )
        }

    throw "Dynamic or SNAPSHOT dependency declaration detected."
}

foreach ($lockRelative in @(
    "app/gradle.lockfile",
    "settings-gradle.lockfile"
)) {
    $lockPath = Join-Path $repoRoot $lockRelative

    if ((Get-Item -LiteralPath $lockPath).Length -le 0) {
        throw "Dependency lockfile is empty: $lockRelative"
    }

    $badLock =
        @(
            Select-String `
                -LiteralPath $lockPath `
                -Pattern @(
                    'SNAPSHOT',
                    'latest\.'
                ) `
                -CaseSensitive:$false
        )

    if ($badLock.Count -gt 0) {
        throw "Dynamic/SNAPSHOT state detected in lockfile: $lockRelative"
    }
}

Write-Host "Supply-chain repository state: PASS"
Write-Host "Verification SHA entries: $($shaMatches.Count)"

foreach ($relative in @(
    "gradle/verification-metadata.xml",
    "app/gradle.lockfile",
    "settings-gradle.lockfile",
    "gradle/wrapper/gradle-wrapper.jar",
    "gradle/wrapper/gradle-wrapper.properties"
)) {
    $full = Join-Path $repoRoot $relative
    $hash =
        (
            Get-FileHash `
                -Algorithm SHA256 `
                -LiteralPath $full
        ).Hash.ToLowerInvariant()

    Write-Host "$relative sha256=$hash"
}
